### ISSUE TITLE
Multiple ar.drones in rviz / preparing own behaviors

### ISSUE THREAD

**Issue by pkaczmarek95** [Vision4UAV/Aerostack#21]
Hello, 

I've got two questions about Aerostack. I would like to know if there is any way to launch a rviz simulation with two or more ar.drones? The other one is about behaviors - is it possible to write own ones?

EDIT: Actually one more thing is bothering me. Could you tell me what are approximate hardware requirements (CPU, GPU and RAM) for fluent running of Aerostack with rviz or gazebo? I tried it with Core2Duo 2,7GHz/Radeon HD7770/4GB RAM and it didn't work out well.

**Comment by martin-molina** [comment]
Hi, we have added some pages explaining how to write your own behaviors:

https://github.com/Vision4UAV/Aerostack/wiki/How-to-Program-a-New-Behavior

**Comment by martin-molina** [comment]
Hi,
This is the configuration what we have used to run Aerostack + Gazebo
CPU: Intel Core i7 (7th Gen)
GPU: Nvidia GEFORCE GTX 1050 Ti
RAM: 16 GB

We have used also Intel Core i5 and 8GB RAM using Ruiz.

**Comment by martin-molina** [comment]
Hi, 
I confirm you that it is possible to launch a RViz simulation with several drones. We are preparing a script to help you with that. We'll let you know when it is ready.

**Comment by albertcp** [comment]
Hi @JacekCieslak95 

I tried to create a new behavior following the tutorial (in order to generate the error you describe) and everything worked fine. For that reason, I have updated the [tutorial](https://github.com/Vision4UAV/Aerostack/wiki/How-to-Program-a-New-Behavior) adding an example of the ```package.xml``` file and the ```CMakeLists.xml``` file.

I hope this helps you.

PS: The step 5 is also updated. It describes that in order to activate the behavior, you just need to launch the behavior created and Aerostack. Then, by calling a ROS service inside the terminal, you can activate the behavior created.

**Comment by JacekCieslak95** [comment]
Everything works fine right now, but I have one more question: I can use my behavior without any problem with python missions, but is it plausible to use it with behavior tree? (my behavior is not shown on list of available behaviors). Should I edit any file?

**Comment by martin-molina** [comment]
Thank you for your message. You are right in your comment, so we are going to correct it. We expect to have it in less than two weeks. We will inform you when this change is done.

**Comment by martin-molina** [comment]
This message is to confirm that the change was already done.
