### ISSUE TITLE
OpenTLD GUI

### ISSUE THREAD

**Issue by hoffa95** [Vision4UAV/Aerostack#23]
Hi,

I am trying to figure out which launch file should I run, if I want to use the OpenTLD GUI and the visual servoing processes. Just like in your cvg_ardrone2_ibvs package. I didn't find any tutorials about this in your Wiki.
It would be nice if you could help me.

Thanks.

**Comment by jespestana** [comment]
Hi hoffa95,

My colleagues from the UPM would be able to tell you the exact launching procedures. Otherwise, my guess is once you download the full stack, you should have in the "launchers" folder the repository:
https://bitbucket.org/Vision4UAV/aerostack_launchers
In this repository there are several launchers for the AR Drone: 
https://bitbucket.org/Vision4UAV/aerostack_launchers/src/835c635c89dfe323f1980d05ebc54af4f87c2613/ardrone_launch/?at=master
I  think that it should work similarly to the cvg_ardrone2_ibvs package once you get it running.

**Comment by hoffa95** [comment]
Thanks for your fast reply! 
My problem solved!

**Comment by mark-91** [comment]
> Hi hoffa95,
> 
> My colleagues from the UPM would be able to tell you the exact launching procedures. Otherwise, my guess is once you download the full stack, you should have in the "launchers" folder the repository: https://bitbucket.org/Vision4UAV/aerostack_launchers In this repository there are several launchers for the AR Drone: https://bitbucket.org/Vision4UAV/aerostack_launchers/src/835c635c89dfe323f1980d05ebc54af4f87c2613/ardrone_launch/?at=master I think that it should work similarly to the cvg_ardrone2_ibvs package once you get it running.

i try to run the code but still do not work 
i see the link and download but i do not know Which script should i run first 
can you please help?
