### ISSUE TITLE
battery 0%

### ISSUE THREAD

**Issue by soheil2017** [Vision4UAV/Aerostack#26]
Hi every one

for the first time I got following problem that i couldn't find any solution for it.  my AR-Drone 2.0 is connected to AeroStack with ubuntu 16.04 (ROS-kinetic) but the battery is showing 0%. but indeed the battery is full charge. also I don't have camera image. in addition I separately  tested it by ardron-autonoumy package and it works perfectly.  I re-started the Ar Drone but Aerostack  doesn't work yet. do you know the problem?

**Comment by albertcp** [comment]
Hi @soheil2017 ,

Did you start Aerostack after being connected to the AR-Drone 2.0?

The steps to initiate Aerostack correctly are:
1. Connect to the ARDrone wifi
2. Ejecute ./ardrone_basic.sh

If you follow these steps and still doesn't work, verify that the launcher is using the correct IP address of the ARDrone.

**Comment by soheil2017** [comment]
dear @albertcp 
I am exactly doing these steps and I also verified  IP address of the ARDrone but it doesn't work yet. I am sure the connection of AR Drone is correct because I tested it with other packages such as ardrone_autonoumy and ORB_SLAM and PTAM.  

![aero](https://user-images.githubusercontent.com/29164834/35859897-0fa30e8a-0b29-11e8-8bd7-14505aecb44a.png)

**Comment by Lowyiiii** [comment]
Hi every one
I have the same problem

**Comment by albertcp** [comment]
Can you check if the drone_id value is the same for all Aerostack processes?

You can do that by typing ```rosnode list``` and also ```rostopic list``` and paste the results here.

**Comment by soheil2017** [comment]
@albertcp 
 this is my rostopic list:

soheil@soheil-X555LNB:~$ rostopic list 
/common_beliefs
/drone1/ArucoSlam_EstimatedPose
/drone1/ArucoSlam_EstimatedPose_v2
/drone1/ArucoSlam_EstimatedSpeed
/drone1/ArucoSlam_EstimatedSpeeds
/drone1/ArucoSlam_LandarmkList
/drone1/EstimatedPose_droneGMR_wrt_GFF
/drone1/EstimatedPose_iRobotGMR_wrt_droneGMR
/drone1/EstimatedSpeed_droneGMR_wrt_GFF
/drone1/SOEstimatedPose
/drone1/SOEstimatedSpeeds
/drone1/all_beliefs
/drone1/altitude
/drone1/approved_action
/drone1/ardrone/bottom/camera_info
/drone1/ardrone/bottom/image_raw
/drone1/ardrone/bottom/image_raw/compressed
/drone1/ardrone/bottom/image_raw/compressed/parameter_descriptions
/drone1/ardrone/bottom/image_raw/compressed/parameter_updates
/drone1/ardrone/bottom/image_raw/compressedDepth
/drone1/ardrone/bottom/image_raw/compressedDepth/parameter_descriptions
/drone1/ardrone/bottom/image_raw/compressedDepth/parameter_updates
/drone1/ardrone/bottom/image_raw/theora
/drone1/ardrone/bottom/image_raw/theora/parameter_descriptions
/drone1/ardrone/bottom/image_raw/theora/parameter_updates
/drone1/ardrone/camera_info
/drone1/ardrone/front/camera_info
/drone1/ardrone/front/image_color
/drone1/ardrone/front/image_color/compressed
/drone1/ardrone/front/image_color/compressed/parameter_descriptions
/drone1/ardrone/front/image_color/compressed/parameter_updates
/drone1/ardrone/front/image_color/compressedDepth
/drone1/ardrone/front/image_color/compressedDepth/parameter_descriptions
/drone1/ardrone/front/image_color/compressedDepth/parameter_updates
/drone1/ardrone/front/image_color/theora
/drone1/ardrone/front/image_color/theora/parameter_descriptions
/drone1/ardrone/front/image_color/theora/parameter_updates
/drone1/ardrone/front/image_mono
/drone1/ardrone/front/image_mono/compressed
/drone1/ardrone/front/image_mono/compressed/parameter_descriptions
/drone1/ardrone/front/image_mono/compressed/parameter_updates
/drone1/ardrone/front/image_mono/compressedDepth
/drone1/ardrone/front/image_mono/compressedDepth/parameter_descriptions
/drone1/ardrone/front/image_mono/compressedDepth/parameter_updates
/drone1/ardrone/front/image_mono/theora
/drone1/ardrone/front/image_mono/theora/parameter_descriptions
/drone1/ardrone/front/image_mono/theora/parameter_updates
/drone1/ardrone/front/image_proc_debayer/parameter_descriptions
/drone1/ardrone/front/image_proc_debayer/parameter_updates
/drone1/ardrone/front/image_proc_rectify_color/parameter_descriptions
/drone1/ardrone/front/image_proc_rectify_color/parameter_updates
/drone1/ardrone/front/image_proc_rectify_mono/parameter_descriptions
/drone1/ardrone/front/image_proc_rectify_mono/parameter_updates
/drone1/ardrone/front/image_raw
/drone1/ardrone/front/image_raw/compressed
/drone1/ardrone/front/image_raw/compressed/parameter_descriptions
/drone1/ardrone/front/image_raw/compressed/parameter_updates
/drone1/ardrone/front/image_raw/compressedDepth
/drone1/ardrone/front/image_raw/compressedDepth/parameter_descriptions
/drone1/ardrone/front/image_raw/compressedDepth/parameter_updates
/drone1/ardrone/front/image_raw/theora
/drone1/ardrone/front/image_raw/theora/parameter_descriptions
/drone1/ardrone/front/image_raw/theora/parameter_updates
/drone1/ardrone/front/image_rect
/drone1/ardrone/front/image_rect/compressed
/drone1/ardrone/front/image_rect/compressed/parameter_descriptions
/drone1/ardrone/front/image_rect/compressed/parameter_updates
/drone1/ardrone/front/image_rect/compressedDepth
/drone1/ardrone/front/image_rect/compressedDepth/parameter_descriptions
/drone1/ardrone/front/image_rect/compressedDepth/parameter_updates
/drone1/ardrone/front/image_rect/theora
/drone1/ardrone/front/image_rect/theora/parameter_descriptions
/drone1/ardrone/front/image_rect/theora/parameter_updates
/drone1/ardrone/front/image_rect_color
/drone1/ardrone/front/image_rect_color/compressed
/drone1/ardrone/front/image_rect_color/compressed/parameter_descriptions
/drone1/ardrone/front/image_rect_color/compressed/parameter_updates
/drone1/ardrone/front/image_rect_color/compressedDepth
/drone1/ardrone/front/image_rect_color/compressedDepth/parameter_descriptions
/drone1/ardrone/front/image_rect_color/compressedDepth/parameter_updates
/drone1/ardrone/front/image_rect_color/theora
/drone1/ardrone/front/image_rect_color/theora/parameter_descriptions
/drone1/ardrone/front/image_rect_color/theora/parameter_updates
/drone1/ardrone/image_raw
/drone1/ardrone/image_raw/compressed
/drone1/ardrone/image_raw/compressed/parameter_descriptions
/drone1/ardrone/image_raw/compressed/parameter_updates
/drone1/ardrone/image_raw/compressedDepth
/drone1/ardrone/image_raw/compressedDepth/parameter_descriptions
/drone1/ardrone/image_raw/compressedDepth/parameter_updates
/drone1/ardrone/image_raw/theora
/drone1/ardrone/image_raw/theora/parameter_descriptions
/drone1/ardrone/image_raw/theora/parameter_updates
/drone1/ardrone/imu
/drone1/ardrone/land
/drone1/ardrone/mag
/drone1/ardrone/navdata
/drone1/ardrone/odometry
/drone1/ardrone/reset
/drone1/ardrone/takeoff
/drone1/arucoObservation
/drone1/aruco_eye/aruco_observation
/drone1/aruco_eye/aruco_observation_image/image_raw
/drone1/aruco_eye/aruco_observation_image/image_raw/compressed
/drone1/aruco_eye/aruco_observation_image/image_raw/compressed/parameter_descriptions
/drone1/aruco_eye/aruco_observation_image/image_raw/compressed/parameter_updates
/drone1/aruco_eye/aruco_observation_image/image_raw/compressedDepth
/drone1/aruco_eye/aruco_observation_image/image_raw/compressedDepth/parameter_descriptions
/drone1/aruco_eye/aruco_observation_image/image_raw/compressedDepth/parameter_updates
/drone1/aruco_eye/aruco_observation_image/image_raw/theora
/drone1/aruco_eye/aruco_observation_image/image_raw/theora/parameter_descriptions
/drone1/aruco_eye/aruco_observation_image/image_raw/theora/parameter_updates
/drone1/battery
/drone1/behavior_event
/drone1/camera/bottom/image_raw
/drone1/camera/front/image_raw
/drone1/camera/overlay/image_raw/big
/drone1/camera/overlay/image_raw/small
/drone1/cmd_vel
/drone1/collision_free_trajectory
/drone1/collision_free_trajectory_preprocessed
/drone1/command/dAltitude
/drone1/command/dYaw
/drone1/command/high_level
/drone1/command/pitch_roll
/drone1/command_PBVS/Altitude
/drone1/completed_action
/drone1/completed_mission
/drone1/controller_image_features
/drone1/controller_image_features_feedback
/drone1/current_task
/drone1/distanceToObstacles
/drone1/droneControllerYawRefCommand
/drone1/droneManagerStatus
/drone1/droneMissionHLCommandAck
/drone1/droneMissionPlannerCommand
/drone1/droneMissionPoint
/drone1/dronePointToLook
/drone1/dronePositionRefs
/drone1/droneSpeedsRefs
/drone1/droneTrajectoryAbsRefCommand
/drone1/droneTrajectoryController/controlMode
/drone1/droneTrajectoryRefCommand
/drone1/droneYawToLook
/drone1/estimated_pose
/drone1/estimated_speed
/drone1/event
/drone1/eventString
/drone1/get_bounding_box
/drone1/ground_speed
/drone1/imu
/drone1/isInTheSystem
/drone1/is_object_on_frame
/drone1/list_of_active_behaviors
/drone1/list_of_active_capabilities
/drone1/list_of_active_processes
/drone1/magnetometer
/drone1/missionState
/drone1/obstacles
/drone1/obstacles_visualization
/drone1/pressure
/drone1/process_alive_signal
/drone1/process_error
/drone1/process_error_unified_notification
/drone1/processes_performance
/drone1/qr_interpretation
/drone1/requested_action
/drone1/rotation_angles
/drone1/self_detected_process_error
/drone1/skills_list
/drone1/societyPose
/drone1/status
/drone1/surface_inspection_image
/drone1/temperature
/drone1/tracking_object
/drone1/trajectoryControllerPositionReferencesRebroadcast
/drone1/trajectoryControllerSpeedReferencesRebroadcast
/drone1/trajectoryControllerTrajectoryReferencesRebroadcast
/drone1/wifiIsOk
/public_event
/rosout
/rosout_agg
/societyBroadcast
/tf
-------------------------------------------
and my rosnode list: 

soheil@soheil-X555LNB:~$ rosnode list 
/drone1/ardrone/front/image_proc
/drone1/ardrone_driver
/drone1/aruco_eye_ros_display_node
/drone1/behavior_coordinator_process
/drone1/behavior_follow_object_image
/drone1/behavior_go_to_point
/drone1/behavior_keep_hovering
/drone1/behavior_keep_moving
/drone1/behavior_land
/drone1/behavior_pay_attention_to_visual_markers
/drone1/behavior_rotate
/drone1/behavior_self_localize_by_odometry
/drone1/behavior_specialist_process
/drone1/behavior_take_off
/drone1/behavior_wait
/drone1/belief_manager_process
/drone1/belief_updater_process
/drone1/bottomCameraARDroneROSModule
/drone1/droneAltitude
/drone1/droneArucoEyeROSModule
/drone1/droneBattery
/drone1/droneCommand
/drone1/droneCommunicationManager
/drone1/droneGroundSpeed
/drone1/droneInterface
/drone1/droneLocalizer
/drone1/droneObstacleDistanceCalculator
/drone1/droneObstacleProcessor
/drone1/droneOdometryStateEstimator
/drone1/droneRotationAngles
/drone1/droneStatusARDroneROSModule
/drone1/droneTrajectoryController
/drone1/droneTrajectoryPlanner
/drone1/droneYawPlanner
/drone1/frontCameraARDroneROSModule
/drone1/graphical_user_interface_process
/drone1/imuARDroneROSModule
/drone1/magnetometerARDroneROSModule
/drone1/pressureARDroneROSModule
/drone1/process_monitor_process_main
/drone1/python_based_mission_interpreter_process
/drone1/resource_manager_process
/drone1/self_localization_selector_process
/drone1/task_based_mission_planner_process
/drone1/temperatureARDroneROSModule
/rosout

**Comment by soheil2017** [comment]
my rostopic list : 

soheil@soheil-X555LNB:~$ rostopic list 
/common_beliefs
/drone1/ArucoSlam_EstimatedPose
/drone1/ArucoSlam_EstimatedPose_v2
/drone1/ArucoSlam_EstimatedSpeed
/drone1/ArucoSlam_EstimatedSpeeds
/drone1/ArucoSlam_LandarmkList
/drone1/EstimatedPose_droneGMR_wrt_GFF
/drone1/EstimatedPose_iRobotGMR_wrt_droneGMR
/drone1/EstimatedSpeed_droneGMR_wrt_GFF
/drone1/SOEstimatedPose
/drone1/SOEstimatedSpeeds
/drone1/all_beliefs
/drone1/altitude
/drone1/approved_action
/drone1/ardrone/bottom/camera_info
/drone1/ardrone/bottom/image_raw
/drone1/ardrone/bottom/image_raw/compressed
/drone1/ardrone/bottom/image_raw/compressed/parameter_descriptions
/drone1/ardrone/bottom/image_raw/compressed/parameter_updates
/drone1/ardrone/bottom/image_raw/compressedDepth
/drone1/ardrone/bottom/image_raw/compressedDepth/parameter_descriptions
/drone1/ardrone/bottom/image_raw/compressedDepth/parameter_updates
/drone1/ardrone/bottom/image_raw/theora
/drone1/ardrone/bottom/image_raw/theora/parameter_descriptions
/drone1/ardrone/bottom/image_raw/theora/parameter_updates
/drone1/ardrone/camera_info
/drone1/ardrone/front/camera_info
/drone1/ardrone/front/image_color
/drone1/ardrone/front/image_color/compressed
/drone1/ardrone/front/image_color/compressed/parameter_descriptions
/drone1/ardrone/front/image_color/compressed/parameter_updates
/drone1/ardrone/front/image_color/compressedDepth
/drone1/ardrone/front/image_color/compressedDepth/parameter_descriptions
/drone1/ardrone/front/image_color/compressedDepth/parameter_updates
/drone1/ardrone/front/image_color/theora
/drone1/ardrone/front/image_color/theora/parameter_descriptions
/drone1/ardrone/front/image_color/theora/parameter_updates
/drone1/ardrone/front/image_mono
/drone1/ardrone/front/image_mono/compressed
/drone1/ardrone/front/image_mono/compressed/parameter_descriptions
/drone1/ardrone/front/image_mono/compressed/parameter_updates
/drone1/ardrone/front/image_mono/compressedDepth
/drone1/ardrone/front/image_mono/compressedDepth/parameter_descriptions
/drone1/ardrone/front/image_mono/compressedDepth/parameter_updates
/drone1/ardrone/front/image_mono/theora
/drone1/ardrone/front/image_mono/theora/parameter_descriptions
/drone1/ardrone/front/image_mono/theora/parameter_updates
/drone1/ardrone/front/image_proc_debayer/parameter_descriptions
/drone1/ardrone/front/image_proc_debayer/parameter_updates
/drone1/ardrone/front/image_proc_rectify_color/parameter_descriptions
/drone1/ardrone/front/image_proc_rectify_color/parameter_updates
/drone1/ardrone/front/image_proc_rectify_mono/parameter_descriptions
/drone1/ardrone/front/image_proc_rectify_mono/parameter_updates
/drone1/ardrone/front/image_raw
/drone1/ardrone/front/image_raw/compressed
/drone1/ardrone/front/image_raw/compressed/parameter_descriptions
/drone1/ardrone/front/image_raw/compressed/parameter_updates
/drone1/ardrone/front/image_raw/compressedDepth
/drone1/ardrone/front/image_raw/compressedDepth/parameter_descriptions
/drone1/ardrone/front/image_raw/compressedDepth/parameter_updates
/drone1/ardrone/front/image_raw/theora
/drone1/ardrone/front/image_raw/theora/parameter_descriptions
/drone1/ardrone/front/image_raw/theora/parameter_updates
/drone1/ardrone/front/image_rect
/drone1/ardrone/front/image_rect/compressed
/drone1/ardrone/front/image_rect/compressed/parameter_descriptions
/drone1/ardrone/front/image_rect/compressed/parameter_updates
/drone1/ardrone/front/image_rect/compressedDepth
/drone1/ardrone/front/image_rect/compressedDepth/parameter_descriptions
/drone1/ardrone/front/image_rect/compressedDepth/parameter_updates
/drone1/ardrone/front/image_rect/theora
/drone1/ardrone/front/image_rect/theora/parameter_descriptions
/drone1/ardrone/front/image_rect/theora/parameter_updates
/drone1/ardrone/front/image_rect_color
/drone1/ardrone/front/image_rect_color/compressed
/drone1/ardrone/front/image_rect_color/compressed/parameter_descriptions
/drone1/ardrone/front/image_rect_color/compressed/parameter_updates
/drone1/ardrone/front/image_rect_color/compressedDepth
/drone1/ardrone/front/image_rect_color/compressedDepth/parameter_descriptions
/drone1/ardrone/front/image_rect_color/compressedDepth/parameter_updates
/drone1/ardrone/front/image_rect_color/theora
/drone1/ardrone/front/image_rect_color/theora/parameter_descriptions
/drone1/ardrone/front/image_rect_color/theora/parameter_updates
/drone1/ardrone/image_raw
/drone1/ardrone/image_raw/compressed
/drone1/ardrone/image_raw/compressed/parameter_descriptions
/drone1/ardrone/image_raw/compressed/parameter_updates
/drone1/ardrone/image_raw/compressedDepth
/drone1/ardrone/image_raw/compressedDepth/parameter_descriptions
/drone1/ardrone/image_raw/compressedDepth/parameter_updates
/drone1/ardrone/image_raw/theora
/drone1/ardrone/image_raw/theora/parameter_descriptions
/drone1/ardrone/image_raw/theora/parameter_updates
/drone1/ardrone/imu
/drone1/ardrone/land
/drone1/ardrone/mag
/drone1/ardrone/navdata
/drone1/ardrone/odometry
/drone1/ardrone/reset
/drone1/ardrone/takeoff
/drone1/arucoObservation
/drone1/aruco_eye/aruco_observation
/drone1/aruco_eye/aruco_observation_image/image_raw
/drone1/aruco_eye/aruco_observation_image/image_raw/compressed
/drone1/aruco_eye/aruco_observation_image/image_raw/compressed/parameter_descriptions
/drone1/aruco_eye/aruco_observation_image/image_raw/compressed/parameter_updates
/drone1/aruco_eye/aruco_observation_image/image_raw/compressedDepth
/drone1/aruco_eye/aruco_observation_image/image_raw/compressedDepth/parameter_descriptions
/drone1/aruco_eye/aruco_observation_image/image_raw/compressedDepth/parameter_updates
/drone1/aruco_eye/aruco_observation_image/image_raw/theora
/drone1/aruco_eye/aruco_observation_image/image_raw/theora/parameter_descriptions
/drone1/aruco_eye/aruco_observation_image/image_raw/theora/parameter_updates
/drone1/battery
/drone1/behavior_event
/drone1/camera/bottom/image_raw
/drone1/camera/front/image_raw
/drone1/camera/overlay/image_raw/big
/drone1/camera/overlay/image_raw/small
/drone1/cmd_vel
/drone1/collision_free_trajectory
/drone1/collision_free_trajectory_preprocessed
/drone1/command/dAltitude
/drone1/command/dYaw
/drone1/command/high_level
/drone1/command/pitch_roll
/drone1/command_PBVS/Altitude
/drone1/completed_action
/drone1/completed_mission
/drone1/controller_image_features
/drone1/controller_image_features_feedback
/drone1/current_task
/drone1/distanceToObstacles
/drone1/droneControllerYawRefCommand
/drone1/droneManagerStatus
/drone1/droneMissionHLCommandAck
/drone1/droneMissionPlannerCommand
/drone1/droneMissionPoint
/drone1/dronePointToLook
/drone1/dronePositionRefs
/drone1/droneSpeedsRefs
/drone1/droneTrajectoryAbsRefCommand
/drone1/droneTrajectoryController/controlMode
/drone1/droneTrajectoryRefCommand
/drone1/droneYawToLook
/drone1/estimated_pose
/drone1/estimated_speed
/drone1/event
/drone1/eventString
/drone1/get_bounding_box
/drone1/ground_speed
/drone1/imu
/drone1/isInTheSystem
/drone1/is_object_on_frame
/drone1/list_of_active_behaviors
/drone1/list_of_active_capabilities
/drone1/list_of_active_processes
/drone1/magnetometer
/drone1/missionState
/drone1/obstacles
/drone1/obstacles_visualization
/drone1/pressure
/drone1/process_alive_signal
/drone1/process_error
/drone1/process_error_unified_notification
/drone1/processes_performance
/drone1/qr_interpretation
/drone1/requested_action
/drone1/rotation_angles
/drone1/self_detected_process_error
/drone1/skills_list
/drone1/societyPose
/drone1/status
/drone1/surface_inspection_image
/drone1/temperature
/drone1/tracking_object
/drone1/trajectoryControllerPositionReferencesRebroadcast
/drone1/trajectoryControllerSpeedReferencesRebroadcast
/drone1/trajectoryControllerTrajectoryReferencesRebroadcast
/drone1/wifiIsOk
/public_event
/rosout
/rosout_agg
/societyBroadcast
/tf
--------------------------------------------------------
my rosnode list: 

soheil@soheil-X555LNB:~$ rosnode list 
/drone1/ardrone/front/image_proc
/drone1/ardrone_driver
/drone1/aruco_eye_ros_display_node
/drone1/behavior_coordinator_process
/drone1/behavior_follow_object_image
/drone1/behavior_go_to_point
/drone1/behavior_keep_hovering
/drone1/behavior_keep_moving
/drone1/behavior_land
/drone1/behavior_pay_attention_to_visual_markers
/drone1/behavior_rotate
/drone1/behavior_self_localize_by_odometry
/drone1/behavior_specialist_process
/drone1/behavior_take_off
/drone1/behavior_wait
/drone1/belief_manager_process
/drone1/belief_updater_process
/drone1/bottomCameraARDroneROSModule
/drone1/droneAltitude
/drone1/droneArucoEyeROSModule
/drone1/droneBattery
/drone1/droneCommand
/drone1/droneCommunicationManager
/drone1/droneGroundSpeed
/drone1/droneInterface
/drone1/droneLocalizer
/drone1/droneObstacleDistanceCalculator
/drone1/droneObstacleProcessor
/drone1/droneOdometryStateEstimator
/drone1/droneRotationAngles
/drone1/droneStatusARDroneROSModule
/drone1/droneTrajectoryController
/drone1/droneTrajectoryPlanner
/drone1/droneYawPlanner
/drone1/frontCameraARDroneROSModule
/drone1/graphical_user_interface_process
/drone1/imuARDroneROSModule
/drone1/magnetometerARDroneROSModule
/drone1/pressureARDroneROSModule
/drone1/process_monitor_process_main
/drone1/python_based_mission_interpreter_process
/drone1/resource_manager_process
/drone1/self_localization_selector_process
/drone1/task_based_mission_planner_process
/drone1/temperatureARDroneROSModule
/rosout

**Comment by albertcp** [comment]
It seems every process is launched correctly and it should connect correctly. Can you check the terminals and see if there are processes that crashed or give some error?

**Comment by Lowyiiii** [comment]
hello @albertcp 
this is my errors
i have the same problem in ardrone and bebop2. also I have found a link that seems the problem is because of drivers
http://wiki.ros.org/kinetic/Migration
========================


[drone1/imuARDroneROSModule-1] process has died [pid 7674, exit code -6, cmd /home/lowyi/workspace/ros/aerostack_catkin_ws/devel/lib/driverParrotARDroneROSModule/imuARDroneROSModule __name:=imuARDroneROSModule __log:=/home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-imuARDroneROSModule-1.log].
log file: /home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-imuARDroneROSModule-1*.log
[drone1/temperatureARDroneROSModule-2] process has died [pid 7687, exit code -6, cmd /home/lowyi/workspace/ros/aerostack_catkin_ws/devel/lib/driverParrotARDroneROSModule/temperatureARDroneROSModule __name:=temperatureARDroneROSModule __log:=/home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-temperatureARDroneROSModule-2.log].
log file: /home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-temperatureARDroneROSModule-2*.log
[drone1/magnetometerARDroneROSModule-3] process has died [pid 7713, exit code -6, cmd /home/lowyi/workspace/ros/aerostack_catkin_ws/devel/lib/driverParrotARDroneROSModule/magnetometerARDroneROSModule __name:=magnetometerARDroneROSModule __log:=/home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-magnetometerARDroneROSModule-3.log].
log file: /home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-magnetometerARDroneROSModule-3*.log
[drone1/droneBattery-4] process has died [pid 7729, exit code -6, cmd /home/lowyi/workspace/ros/aerostack_catkin_ws/devel/lib/driverParrotARDroneROSModule/batteryARDroneROSModule __name:=droneBattery __log:=/home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-droneBattery-4.log].
log file: /home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-droneBattery-4*.log
[drone1/droneAltitude-5] process has died [pid 7747, exit code -6, cmd /home/lowyi/workspace/ros/aerostack_catkin_ws/devel/lib/driverParrotARDroneROSModule/altitudeARDroneROSModule __name:=droneAltitude __log:=/home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-droneAltitude-5.log].
log file: /home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-droneAltitude-5*.log
[drone1/droneRotationAngles-6] process has died [pid 7763, exit code -6, cmd /home/lowyi/workspace/ros/aerostack_catkin_ws/devel/lib/driverParrotARDroneROSModule/rotationAnglesARDroneROSModule __name:=droneRotationAngles __log:=/home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-droneRotationAngles-6.log].
log file: /home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-droneRotationAngles-6*.log
[drone1/droneGroundSpeed-7] process has died [pid 7787, exit code -6, cmd /home/lowyi/workspace/ros/aerostack_catkin_ws/devel/lib/driverParrotARDroneROSModule/groundSpeedARDroneROSModule __name:=droneGroundSpeed __log:=/home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-droneGroundSpeed-7.log].
log file: /home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-droneGroundSpeed-7*.log
[drone1/pressureARDroneROSModule-8] process has died [pid 7804, exit code -6, cmd /home/lowyi/workspace/ros/aerostack_catkin_ws/devel/lib/driverParrotARDroneROSModule/pressureARDroneROSModule __name:=pressureARDroneROSModule __log:=/home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-pressureARDroneROSModule-8.log].
log file: /home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-pressureARDroneROSModule-8*.log
[drone1/frontCameraARDroneROSModule-11] process has died [pid 7849, exit code -6, cmd /home/lowyi/workspace/ros/aerostack_catkin_ws/devel/lib/driverParrotARDroneROSModule/frontCameraARDroneROSModule __name:=frontCameraARDroneROSModule __log:=/home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-frontCameraARDroneROSModule-11.log].
log file: /home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-frontCameraARDroneROSModule-11*.log
[drone1/droneCommand-12] process has died [pid 7855, exit code -6, cmd /home/lowyi/workspace/ros/aerostack_catkin_ws/devel/lib/driverParrotARDroneROSModule/droneCommandARDroneROSModule __name:=droneCommand __log:=/home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-droneCommand-12.log].
log file: /home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-droneCommand-12*.log
[drone1/droneStatusARDroneROSModule-9] process has died [pid 7827, exit code -6, cmd /home/lowyi/workspace/ros/aerostack_catkin_ws/devel/lib/driverParrotARDroneROSModule/droneStatusARDroneROSModule __name:=droneStatusARDroneROSModule __log:=/home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-droneStatusARDroneROSModule-9.log].
log file: /home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-droneStatusARDroneROSModule-9*.log
[drone1/bottomCameraARDroneROSModule-10] process has died [pid 7834, exit code -6, cmd /home/lowyi/workspace/ros/aerostack_catkin_ws/devel/lib/driverParrotARDroneROSModule/bottomCameraARDroneROSModule __name:=bottomCameraARDroneROSModule __log:=/home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-bottomCameraARDroneROSModule-10.log].
log file: /home/lowyi/.ros/log/99aafe02-0d96-11e8-b4ab-6817298b2a6d/drone1-bottomCameraARDroneROSModule-10*.log

**Comment by soheil2017** [comment]
@albertcp 
thanks for realizing the new version of AeroStack. in new version, the problem of my battery is solved.
