### ISSUE TITLE
about TML

### ISSUE THREAD

**Issue by pigeonsL** [Vision4UAV/Aerostack#41]
Hello, I have been paying attention to Aerostack, this is a great project. I want to ask  why  the version 3.0 does not have TML?

**Comment by martin-molina** [comment]
Thank you for your interest and your comment. We have not included TML in version 3.0 mainly because this version includes a new execution control system that is not directly compatible with TML. We can include TML in future versions of Aerostack (but this depends on our research on mission representation languages).
